### ISSUE TITLE
Errors of patch

### ISSUE THREAD

**Issue by DeepakIngole** [NaleRaphael/cartpole-control#2]
I am trying to run your codes on macOS BigSur 11.1 with PyChram 2020.3. While running main.py I'm getting the following errors. Would you please help me to resolve the errors? Which versions of the gym, TensorFlow python, etc. I will need? Thanks.

Failed to patch `CartPoleEnv.__init__`Traceback (most recent call last):
  File "/Users/xxxx/Documents/Python_Deepak/cartpole-control-master/main.py", line 6, in <module>
    from cpc.env import CartPoleEnv, AdvancedCartPoleEnv
  File "/Users/xxxx/Documents/Python_Deepak/cartpole-control-master/cpc/__init__.py", line 94, in <module>
    CartPoleEnv.__init__ = dirty_patch(CartPoleEnv.__init__)
  File "/Users/xxxx/Documents/Python_Deepak/cartpole-control-master/cpc/__init__.py", line 52, in dirty_patch
    idx_call = payload.index(ins)
ValueError: subsection not found

**Comment by NaleRaphael** [comment]
Hi @DeepakIngole, that error message seems not related to the version of gym or TensorFlow, I may need further details to investigate the issue. But I also just add a `requirement.txt` to the latest commit, you can try to pull the latest version of this repo and use the following command to install dependencies:
```bash
$ pip install -r ./requirements.txt
```

But note that it's recommended to install them **in a new virtual environment** to avoid those old dependencies messing your environment up since this repository was built about 2 years ago, and I don't have too much free time to keep it updated.

Besides, I was running experiments on a CPU-only environment before. So that there might be some issues related to CUDA libraries if you want to run it with `tensorflow-gpu`, and you might need to solve them on your own. I'm sorry about it.

But if you have any further questions, please feel free to let me know.

**Comment by NaleRaphael** [comment]
By the way, if you want to run this repository with `tensorflow>=2` and newer version of `openai-gym`, you can remove code related to dirty patch in `cpc/__init__,py`. That dirty patch was just made for `openai-gym==1.10`, so it might not work in newer versions.

But It might take you some time to solve errors resulted by different versions of libraries since there would be some deprecated/removed APIs, just make sure you have enough free time before doing it.
